css/style.css
index.html
js/app.js

<ul>
<li> Changed Image Rendering to Canvas-based</li>
<li> Added GreyScale Filter</li>
<li>Made Save Button Functional</li>
<li>Improved Button Animations</li>
</ul>
Change Image Rendering Method https://github.com/gdscjgec/Image-Editor/issues/10
Add Black and White Filter https://github.com/gdscjgec/Image-Editor/issues/8

feat: GreyScale Filter & Canvas Rendering

---

css/style.css
index.html

Made the website fully responsive.

---

css/style.css
index.html
js/app.js

<ul>
<li>Feat: Added Undo and Redo Functions (Single Step)</li>
<li>Feat: Added Button Animations for Undo and Redo</li>
<li>Update: Added a Case-Switch method to call filters as it was necessary to perform Change Control (Undo/Redo)</li>
<li>Update: Changed <code>&lt;a&gt;</code> tag in buttons to <code>&lt;div&gt;</code> to remove annoying href page bug</li>
<li>Fix: Fixed double download issue when using the Save Now button</li>
<li>Fix: typo from onClick to onclick in some elements</li>
</ul>
Redo Button: https://github.com/gdscjgec/Image-Editor/issues/7
Undo Button: https://github.com/gdscjgec/Image-Editor/issues/6

Feat: Undo and Redo Feature + Bug Fixes

---

css/style.css

I've fixed the uploaded image preview to center, issues [#2 ](https://github.com/gdscjgec/Image-Editor/issues/2)
The image is not center because of position: absolute.

Fixing uploaded image preview

---

css/style.css
index.html
js/app.js

added Dark mood feature

---

css/style.css
index.html
js/app.js

The issue was to create range sliders to edit image insted of buttons
I have done that and added required Javascript and css too 
Convert The filter buttons into Sliders #18

filters button into sliders added

---

css/style.css
index.html
js/app.js

Reverts gdscjgec/Image-Editor#26
Please check there is an issue with the image upload section

Revert "filters button into sliders added"

---

css/style.css
index.html
js/app.js

Added a toggle button to switch between light and dark modes in website
- [ yes] I am making a proper pull request, not spam.
- [ yes] I've checked the issue list before deciding what to submit.
None

added toggle button for light/dark mode

---

css/style.css

Button animation

---

css/style.css

I have removed all the borders form the editor and canvas section.

removed border

---

css/style.css
index.html
js/app.js

- Added Icons to some features
- Icons for Dark and Light mode that change
- Backgrounds for effects
Issue #14
Run the app locally to see the effects

Add Styling and Icons

---

js/app.js

Fix save button

---

css/style.css
index.html

Changed By Shreyan

---

README.md
css/style.css
index.html

reupdated html css and readme file
(Add here)

this is my 1st contribution to open source

---

css/style.css

Issue #69 I have fixed the image distortion bug as JWoC contribution
I had to change some css to make it happen
Thanks, Kindly merge my PR

issue #69 image distortion bug fixed

---

css/style.css
index.html
js/app.js

implemented 5 different filters - flip (to make the image negative), rainbow (to add rainbow effect to the picture), crumble (to give crumbled paper effect to image), sunset (to apply reddish orange tint as of sunset to image, prison (to add prison like bars to image)
Implement other useful Filter - issue #9 
below pictures in order as - buttons, original image, flip, rainbow, crumble, sunset, prison
#9

implementation of other useful Filter as of #9

---

css/style.css
index.html
js/app.js

- [yes ] I am making a proper pull request, not spam.
- [yes ] I've checked the issue list before deciding what to submit.
Dear Mentor plz let me know if The changes are properly working or i have to work more on it.
(Add here)

Image Resizer Tool is successfully added

---

css/style.css
index.html

Enhanced the overall Styling.
Enhanced the overall Styling.
issue no  #14
(Add here)

Enhanced the overall Styling.

---

assets/svg/download.svg
css/range-input.css
css/style.css
css/styleOld.css
index.html
pages/index.html

Redesigned the page in accord with the prototype.
In response to issue: #75

Redesigned the page

---

index.html
js/app.js

Added blur slider to change the image blur intensity.
#86

Add blur slider

---

css/style.css

Made the page responsive
In response to issue: #91 
https://user-images.githubusercontent.com/72697074/154920264-1b2ed409-bbf6-48fb-b273-49f92be793a7.mp4

Made the webpage responsive

---

index.html
js/app.js

Added a opacity slider to adjust the image opacity.
#89

Add opacity slider

---

css/style.css
index.html
js/app.js

Implemented different filters like saturation to make colors more vivid or more muted, hue rotate to set the hue rotation of the image.
#9

Implement different filters

---

.vscode/settings.json
css/style.css
index.html

Enhanced the overall styling
deployed link : https://sayan404.github.io/Image-Editor/
(Add here)

Enhanced the overall styling

---

assets/favicon/site.webmanifest
css/style.css
index.html
manifest.json
offline.html
serviceworker.js

I transform the application to a progressive web app which will enable user to be able to install it on their machine.
- I am making a proper pull request, not spam.
- I've checked the issue list before deciding what to submit.
Issues #93

transform to progresive web app
